version: '3'
services:
  mongodbserver:
    image: mongo:7.0.4
    restart: no
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
        - ./mongodb-data:/data/db
